#!/usr/bin/env ruby

class SitesCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    sites.select do |task|
      task[0, typed.length] == typed
    end
  end
  
  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def sites
    `ls ~/Sites/`.split
  end
end

puts SitesCompletion.new(ENV["COMP_LINE"]).matches
exit 0