#!/bin/sh

# Change default text editor to TextMate
export EDITOR="mate -w"

# When adding items to history, remove duplicates upstream
export HISTCONTROL=erasedups
export HISTSIZE=3000

# Ruby
export RUBYOPT=rubygems
export RUBYLIB="$DOTFILES/lib"

# Path
export PATH="/usr/local/bin:/Developer/Tools:$DOTFILES/bin:$PATH"

# function to return current branch name while suppressing errors.
function git_branch() {
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')

  if [[ $branch == "" ]]; then
    :
  else
    echo '['$branch']'
  fi
}

setopt prompt_subst # allow command substitution inside the prompt
export PROMPT='%B%~$(git_branch) $%b ' # set the prompt value
